### ISSUE TITLE
如果命令里面没有 title、password ，能否直接用默认值，不用二次确认

### ISSUE THREAD

**Issue by wisinfun** [Aixzk/uploader#1]
![image](https://user-images.githubusercontent.com/41355260/193444161-1f1a694d-4f22-45a9-8680-a294bb4c0cf4.png)

**Comment by Pandaft** [comment]
已修改，使用最新版 `v0.1.4` 试试。

**Comment by wisinfun** [comment]
> 已修改，使用最新版 `v0.1.4` 试试。

OK啦，辛苦佬哥了
