### ISSUE TITLE
上传后文件名不一致（MacOS）

### ISSUE THREAD

**Issue by wisinfun** [Aixzk/uploader#2]
--upload_path /Users/ym/Downloads/uploader_macos-11.0.tar.gz
<img width="641" alt="image" src="https://user-images.githubusercontent.com/41355260/193456432-e516bf1c-c0ca-416f-aea2-c7a9c77b4de8.png">

**Comment by Pandaft** [comment]
问题确认，请等待修复。

**Comment by Pandaft** [comment]
试试最新版。

**Comment by wisinfun** [comment]
@Pandaft 已经正常了，佬哥辛苦啦
